/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AlignerCase {
  'id' : AlignerCaseId,
  'currentPhase' : string,
  'endDate' : [] | [string],
  'patientId' : PatientId,
  'clinicId' : ClinicId,
  'stage' : string,
  'alignersCompleted' : bigint,
  'hasRefinements' : boolean,
  'startDate' : string,
  'totalAligners' : bigint,
}
export type AlignerCaseId = number;
export interface AnalyticsResponse {
  'followUpsDueToday' : Array<[TreatmentId, string]>,
  'overdueFollowUps' : Array<[TreatmentId, string]>,
}
export interface Clinic {
  'id' : ClinicId,
  'name' : string,
  'address' : string,
  'phoneNumber' : string,
}
export interface ClinicCreation {
  'name' : string,
  'address' : string,
  'phoneNumber' : string,
}
export type ClinicId = number;
export type FeedbackId = number;
export interface ImplantCase {
  'id' : ImplantCaseId,
  'healingStartDate' : [] | [string],
  'patientId' : PatientId,
  'clinicId' : ClinicId,
  'crownPlacementDate' : [] | [string],
  'stage' : string,
  'surgeryDate' : [] | [string],
}
export type ImplantCaseId = number;
export interface NewAlignerCaseView {
  'currentPhase' : string,
  'endDate' : [] | [string],
  'patientId' : PatientId,
  'clinicId' : ClinicId,
  'stage' : string,
  'alignersCompleted' : bigint,
  'hasRefinements' : boolean,
  'startDate' : string,
  'totalAligners' : bigint,
}
export interface NewImplantCaseView {
  'healingStartDate' : [] | [string],
  'patientId' : PatientId,
  'clinicId' : ClinicId,
  'crownPlacementDate' : [] | [string],
  'stage' : string,
  'surgeryDate' : [] | [string],
}
export interface NewPatientFeedbackView {
  'patientId' : PatientId,
  'clinicId' : ClinicId,
  'date' : string,
  'feedback' : string,
  'googleReviewCompleted' : boolean,
  'rating' : number,
}
export interface NewTreatmentView {
  'status' : string,
  'teeth' : Uint8Array,
  'endDate' : [] | [string],
  'doctor' : string,
  'patientId' : PatientId,
  'clinicId' : ClinicId,
  'type' : string,
  'totalUnitsNeeded' : bigint,
  'unitsCompleted' : bigint,
  'followUpDates' : Array<string>,
  'startDate' : string,
}
export interface Patient {
  'id' : PatientId,
  'dob' : string,
  'clinicId' : ClinicId,
  'name' : string,
  'email' : string,
  'address' : string,
  'gender' : string,
  'phoneNumber' : string,
}
export interface PatientFeedback {
  'id' : FeedbackId,
  'patientId' : PatientId,
  'clinicId' : ClinicId,
  'date' : string,
  'feedback' : string,
  'googleReviewCompleted' : boolean,
  'rating' : number,
}
export type PatientId = number;
export type ToothNumber = number;
export type TreatmentId = number;
export interface TreatmentView {
  'id' : TreatmentId,
  'status' : string,
  'teeth' : Uint8Array,
  'endDate' : [] | [string],
  'doctor' : string,
  'patientId' : PatientId,
  'clinicId' : ClinicId,
  'type' : string,
  'totalUnitsNeeded' : bigint,
  'unitsCompleted' : bigint,
  'followUpDates' : Array<string>,
  'startDate' : string,
}
export interface UserProfile { 'clinicId' : [] | [ClinicId], 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAlignerCase' : ActorMethod<[NewAlignerCaseView], AlignerCaseId>,
  'addImplantCase' : ActorMethod<[NewImplantCaseView], ImplantCaseId>,
  'addPatient' : ActorMethod<[Patient], PatientId>,
  'addPatientFeedback' : ActorMethod<[NewPatientFeedbackView], FeedbackId>,
  'addTreatment' : ActorMethod<[NewTreatmentView], TreatmentId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createClinic' : ActorMethod<[ClinicCreation], Clinic>,
  'deleteAlignerCase' : ActorMethod<[AlignerCaseId], undefined>,
  'deleteClinic' : ActorMethod<[ClinicId], undefined>,
  'deleteImplantCase' : ActorMethod<[ImplantCaseId], undefined>,
  'deletePatient' : ActorMethod<[PatientId], undefined>,
  'deletePatientFeedback' : ActorMethod<[FeedbackId], undefined>,
  'deleteTreatment' : ActorMethod<[TreatmentId], undefined>,
  'getAlignerCase' : ActorMethod<[AlignerCaseId], [] | [AlignerCase]>,
  'getAllAlignerCases' : ActorMethod<[], Array<AlignerCase>>,
  'getAllClinics' : ActorMethod<[], Array<Clinic>>,
  'getAllImplantCases' : ActorMethod<[], Array<ImplantCase>>,
  'getAllPatientFeedback' : ActorMethod<[], Array<PatientFeedback>>,
  'getAllPatients' : ActorMethod<[], Array<Patient>>,
  'getAllTreatments' : ActorMethod<[], Array<TreatmentView>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClinic' : ActorMethod<[ClinicId], [] | [Clinic]>,
  'getFollowUpAnalytics' : ActorMethod<[], AnalyticsResponse>,
  'getImplantCase' : ActorMethod<[ImplantCaseId], [] | [ImplantCase]>,
  'getPatient' : ActorMethod<[PatientId], [] | [Patient]>,
  'getPatientFeedback' : ActorMethod<[FeedbackId], [] | [PatientFeedback]>,
  'getTreatment' : ActorMethod<[TreatmentId], [] | [TreatmentView]>,
  'getUpcomingFollowUps' : ActorMethod<[], Array<[TreatmentId, string]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'scheduleFollowUp' : ActorMethod<[TreatmentId, string], undefined>,
  'updateAlignerCase' : ActorMethod<[AlignerCase], undefined>,
  'updateAlignerCaseStage' : ActorMethod<[AlignerCaseId, string], undefined>,
  'updateClinic' : ActorMethod<[Clinic], undefined>,
  'updateImplantCase' : ActorMethod<[ImplantCase], undefined>,
  'updateImplantCaseStage' : ActorMethod<[ImplantCaseId, string], undefined>,
  'updatePatient' : ActorMethod<[Patient], undefined>,
  'updatePatientFeedback' : ActorMethod<[PatientFeedback], undefined>,
  'updateTreatment' : ActorMethod<[TreatmentView], undefined>,
  'updateTreatmentProgress' : ActorMethod<[TreatmentId, bigint], undefined>,
  'updateTreatmentStatus' : ActorMethod<[TreatmentId, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];