/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PatientId = IDL.Nat32;
export const ClinicId = IDL.Nat32;
export const NewAlignerCaseView = IDL.Record({
  'currentPhase' : IDL.Text,
  'endDate' : IDL.Opt(IDL.Text),
  'patientId' : PatientId,
  'clinicId' : ClinicId,
  'stage' : IDL.Text,
  'alignersCompleted' : IDL.Nat,
  'hasRefinements' : IDL.Bool,
  'startDate' : IDL.Text,
  'totalAligners' : IDL.Nat,
});
export const AlignerCaseId = IDL.Nat32;
export const NewImplantCaseView = IDL.Record({
  'healingStartDate' : IDL.Opt(IDL.Text),
  'patientId' : PatientId,
  'clinicId' : ClinicId,
  'crownPlacementDate' : IDL.Opt(IDL.Text),
  'stage' : IDL.Text,
  'surgeryDate' : IDL.Opt(IDL.Text),
});
export const ImplantCaseId = IDL.Nat32;
export const Patient = IDL.Record({
  'id' : PatientId,
  'dob' : IDL.Text,
  'clinicId' : ClinicId,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'gender' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const NewPatientFeedbackView = IDL.Record({
  'patientId' : PatientId,
  'clinicId' : ClinicId,
  'date' : IDL.Text,
  'feedback' : IDL.Text,
  'googleReviewCompleted' : IDL.Bool,
  'rating' : IDL.Nat8,
});
export const FeedbackId = IDL.Nat32;
export const NewTreatmentView = IDL.Record({
  'status' : IDL.Text,
  'teeth' : IDL.Vec(IDL.Nat8),
  'endDate' : IDL.Opt(IDL.Text),
  'doctor' : IDL.Text,
  'patientId' : PatientId,
  'clinicId' : ClinicId,
  'type' : IDL.Text,
  'totalUnitsNeeded' : IDL.Nat,
  'unitsCompleted' : IDL.Nat,
  'followUpDates' : IDL.Vec(IDL.Text),
  'startDate' : IDL.Text,
});
export const TreatmentId = IDL.Nat32;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ClinicCreation = IDL.Record({
  'name' : IDL.Text,
  'address' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const Clinic = IDL.Record({
  'id' : ClinicId,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const AlignerCase = IDL.Record({
  'id' : AlignerCaseId,
  'currentPhase' : IDL.Text,
  'endDate' : IDL.Opt(IDL.Text),
  'patientId' : PatientId,
  'clinicId' : ClinicId,
  'stage' : IDL.Text,
  'alignersCompleted' : IDL.Nat,
  'hasRefinements' : IDL.Bool,
  'startDate' : IDL.Text,
  'totalAligners' : IDL.Nat,
});
export const ImplantCase = IDL.Record({
  'id' : ImplantCaseId,
  'healingStartDate' : IDL.Opt(IDL.Text),
  'patientId' : PatientId,
  'clinicId' : ClinicId,
  'crownPlacementDate' : IDL.Opt(IDL.Text),
  'stage' : IDL.Text,
  'surgeryDate' : IDL.Opt(IDL.Text),
});
export const PatientFeedback = IDL.Record({
  'id' : FeedbackId,
  'patientId' : PatientId,
  'clinicId' : ClinicId,
  'date' : IDL.Text,
  'feedback' : IDL.Text,
  'googleReviewCompleted' : IDL.Bool,
  'rating' : IDL.Nat8,
});
export const ToothNumber = IDL.Nat8;
export const TreatmentView = IDL.Record({
  'id' : TreatmentId,
  'status' : IDL.Text,
  'teeth' : IDL.Vec(ToothNumber),
  'endDate' : IDL.Opt(IDL.Text),
  'doctor' : IDL.Text,
  'patientId' : PatientId,
  'clinicId' : ClinicId,
  'type' : IDL.Text,
  'totalUnitsNeeded' : IDL.Nat,
  'unitsCompleted' : IDL.Nat,
  'followUpDates' : IDL.Vec(IDL.Text),
  'startDate' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'clinicId' : IDL.Opt(ClinicId),
  'name' : IDL.Text,
});
export const AnalyticsResponse = IDL.Record({
  'followUpsDueToday' : IDL.Vec(IDL.Tuple(TreatmentId, IDL.Text)),
  'overdueFollowUps' : IDL.Vec(IDL.Tuple(TreatmentId, IDL.Text)),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAlignerCase' : IDL.Func([NewAlignerCaseView], [AlignerCaseId], []),
  'addImplantCase' : IDL.Func([NewImplantCaseView], [ImplantCaseId], []),
  'addPatient' : IDL.Func([Patient], [PatientId], []),
  'addPatientFeedback' : IDL.Func([NewPatientFeedbackView], [FeedbackId], []),
  'addTreatment' : IDL.Func([NewTreatmentView], [TreatmentId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createClinic' : IDL.Func([ClinicCreation], [Clinic], []),
  'deleteAlignerCase' : IDL.Func([AlignerCaseId], [], []),
  'deleteClinic' : IDL.Func([ClinicId], [], []),
  'deleteImplantCase' : IDL.Func([ImplantCaseId], [], []),
  'deletePatient' : IDL.Func([PatientId], [], []),
  'deletePatientFeedback' : IDL.Func([FeedbackId], [], []),
  'deleteTreatment' : IDL.Func([TreatmentId], [], []),
  'getAlignerCase' : IDL.Func(
      [AlignerCaseId],
      [IDL.Opt(AlignerCase)],
      ['query'],
    ),
  'getAllAlignerCases' : IDL.Func([], [IDL.Vec(AlignerCase)], ['query']),
  'getAllClinics' : IDL.Func([], [IDL.Vec(Clinic)], ['query']),
  'getAllImplantCases' : IDL.Func([], [IDL.Vec(ImplantCase)], ['query']),
  'getAllPatientFeedback' : IDL.Func([], [IDL.Vec(PatientFeedback)], ['query']),
  'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
  'getAllTreatments' : IDL.Func([], [IDL.Vec(TreatmentView)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClinic' : IDL.Func([ClinicId], [IDL.Opt(Clinic)], ['query']),
  'getFollowUpAnalytics' : IDL.Func([], [AnalyticsResponse], ['query']),
  'getImplantCase' : IDL.Func(
      [ImplantCaseId],
      [IDL.Opt(ImplantCase)],
      ['query'],
    ),
  'getPatient' : IDL.Func([PatientId], [IDL.Opt(Patient)], ['query']),
  'getPatientFeedback' : IDL.Func(
      [FeedbackId],
      [IDL.Opt(PatientFeedback)],
      ['query'],
    ),
  'getTreatment' : IDL.Func([TreatmentId], [IDL.Opt(TreatmentView)], ['query']),
  'getUpcomingFollowUps' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(TreatmentId, IDL.Text))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'scheduleFollowUp' : IDL.Func([TreatmentId, IDL.Text], [], []),
  'updateAlignerCase' : IDL.Func([AlignerCase], [], []),
  'updateAlignerCaseStage' : IDL.Func([AlignerCaseId, IDL.Text], [], []),
  'updateClinic' : IDL.Func([Clinic], [], []),
  'updateImplantCase' : IDL.Func([ImplantCase], [], []),
  'updateImplantCaseStage' : IDL.Func([ImplantCaseId, IDL.Text], [], []),
  'updatePatient' : IDL.Func([Patient], [], []),
  'updatePatientFeedback' : IDL.Func([PatientFeedback], [], []),
  'updateTreatment' : IDL.Func([TreatmentView], [], []),
  'updateTreatmentProgress' : IDL.Func([TreatmentId, IDL.Nat], [], []),
  'updateTreatmentStatus' : IDL.Func([TreatmentId, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PatientId = IDL.Nat32;
  const ClinicId = IDL.Nat32;
  const NewAlignerCaseView = IDL.Record({
    'currentPhase' : IDL.Text,
    'endDate' : IDL.Opt(IDL.Text),
    'patientId' : PatientId,
    'clinicId' : ClinicId,
    'stage' : IDL.Text,
    'alignersCompleted' : IDL.Nat,
    'hasRefinements' : IDL.Bool,
    'startDate' : IDL.Text,
    'totalAligners' : IDL.Nat,
  });
  const AlignerCaseId = IDL.Nat32;
  const NewImplantCaseView = IDL.Record({
    'healingStartDate' : IDL.Opt(IDL.Text),
    'patientId' : PatientId,
    'clinicId' : ClinicId,
    'crownPlacementDate' : IDL.Opt(IDL.Text),
    'stage' : IDL.Text,
    'surgeryDate' : IDL.Opt(IDL.Text),
  });
  const ImplantCaseId = IDL.Nat32;
  const Patient = IDL.Record({
    'id' : PatientId,
    'dob' : IDL.Text,
    'clinicId' : ClinicId,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'gender' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const NewPatientFeedbackView = IDL.Record({
    'patientId' : PatientId,
    'clinicId' : ClinicId,
    'date' : IDL.Text,
    'feedback' : IDL.Text,
    'googleReviewCompleted' : IDL.Bool,
    'rating' : IDL.Nat8,
  });
  const FeedbackId = IDL.Nat32;
  const NewTreatmentView = IDL.Record({
    'status' : IDL.Text,
    'teeth' : IDL.Vec(IDL.Nat8),
    'endDate' : IDL.Opt(IDL.Text),
    'doctor' : IDL.Text,
    'patientId' : PatientId,
    'clinicId' : ClinicId,
    'type' : IDL.Text,
    'totalUnitsNeeded' : IDL.Nat,
    'unitsCompleted' : IDL.Nat,
    'followUpDates' : IDL.Vec(IDL.Text),
    'startDate' : IDL.Text,
  });
  const TreatmentId = IDL.Nat32;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ClinicCreation = IDL.Record({
    'name' : IDL.Text,
    'address' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const Clinic = IDL.Record({
    'id' : ClinicId,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const AlignerCase = IDL.Record({
    'id' : AlignerCaseId,
    'currentPhase' : IDL.Text,
    'endDate' : IDL.Opt(IDL.Text),
    'patientId' : PatientId,
    'clinicId' : ClinicId,
    'stage' : IDL.Text,
    'alignersCompleted' : IDL.Nat,
    'hasRefinements' : IDL.Bool,
    'startDate' : IDL.Text,
    'totalAligners' : IDL.Nat,
  });
  const ImplantCase = IDL.Record({
    'id' : ImplantCaseId,
    'healingStartDate' : IDL.Opt(IDL.Text),
    'patientId' : PatientId,
    'clinicId' : ClinicId,
    'crownPlacementDate' : IDL.Opt(IDL.Text),
    'stage' : IDL.Text,
    'surgeryDate' : IDL.Opt(IDL.Text),
  });
  const PatientFeedback = IDL.Record({
    'id' : FeedbackId,
    'patientId' : PatientId,
    'clinicId' : ClinicId,
    'date' : IDL.Text,
    'feedback' : IDL.Text,
    'googleReviewCompleted' : IDL.Bool,
    'rating' : IDL.Nat8,
  });
  const ToothNumber = IDL.Nat8;
  const TreatmentView = IDL.Record({
    'id' : TreatmentId,
    'status' : IDL.Text,
    'teeth' : IDL.Vec(ToothNumber),
    'endDate' : IDL.Opt(IDL.Text),
    'doctor' : IDL.Text,
    'patientId' : PatientId,
    'clinicId' : ClinicId,
    'type' : IDL.Text,
    'totalUnitsNeeded' : IDL.Nat,
    'unitsCompleted' : IDL.Nat,
    'followUpDates' : IDL.Vec(IDL.Text),
    'startDate' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'clinicId' : IDL.Opt(ClinicId),
    'name' : IDL.Text,
  });
  const AnalyticsResponse = IDL.Record({
    'followUpsDueToday' : IDL.Vec(IDL.Tuple(TreatmentId, IDL.Text)),
    'overdueFollowUps' : IDL.Vec(IDL.Tuple(TreatmentId, IDL.Text)),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAlignerCase' : IDL.Func([NewAlignerCaseView], [AlignerCaseId], []),
    'addImplantCase' : IDL.Func([NewImplantCaseView], [ImplantCaseId], []),
    'addPatient' : IDL.Func([Patient], [PatientId], []),
    'addPatientFeedback' : IDL.Func([NewPatientFeedbackView], [FeedbackId], []),
    'addTreatment' : IDL.Func([NewTreatmentView], [TreatmentId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createClinic' : IDL.Func([ClinicCreation], [Clinic], []),
    'deleteAlignerCase' : IDL.Func([AlignerCaseId], [], []),
    'deleteClinic' : IDL.Func([ClinicId], [], []),
    'deleteImplantCase' : IDL.Func([ImplantCaseId], [], []),
    'deletePatient' : IDL.Func([PatientId], [], []),
    'deletePatientFeedback' : IDL.Func([FeedbackId], [], []),
    'deleteTreatment' : IDL.Func([TreatmentId], [], []),
    'getAlignerCase' : IDL.Func(
        [AlignerCaseId],
        [IDL.Opt(AlignerCase)],
        ['query'],
      ),
    'getAllAlignerCases' : IDL.Func([], [IDL.Vec(AlignerCase)], ['query']),
    'getAllClinics' : IDL.Func([], [IDL.Vec(Clinic)], ['query']),
    'getAllImplantCases' : IDL.Func([], [IDL.Vec(ImplantCase)], ['query']),
    'getAllPatientFeedback' : IDL.Func(
        [],
        [IDL.Vec(PatientFeedback)],
        ['query'],
      ),
    'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
    'getAllTreatments' : IDL.Func([], [IDL.Vec(TreatmentView)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClinic' : IDL.Func([ClinicId], [IDL.Opt(Clinic)], ['query']),
    'getFollowUpAnalytics' : IDL.Func([], [AnalyticsResponse], ['query']),
    'getImplantCase' : IDL.Func(
        [ImplantCaseId],
        [IDL.Opt(ImplantCase)],
        ['query'],
      ),
    'getPatient' : IDL.Func([PatientId], [IDL.Opt(Patient)], ['query']),
    'getPatientFeedback' : IDL.Func(
        [FeedbackId],
        [IDL.Opt(PatientFeedback)],
        ['query'],
      ),
    'getTreatment' : IDL.Func(
        [TreatmentId],
        [IDL.Opt(TreatmentView)],
        ['query'],
      ),
    'getUpcomingFollowUps' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(TreatmentId, IDL.Text))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'scheduleFollowUp' : IDL.Func([TreatmentId, IDL.Text], [], []),
    'updateAlignerCase' : IDL.Func([AlignerCase], [], []),
    'updateAlignerCaseStage' : IDL.Func([AlignerCaseId, IDL.Text], [], []),
    'updateClinic' : IDL.Func([Clinic], [], []),
    'updateImplantCase' : IDL.Func([ImplantCase], [], []),
    'updateImplantCaseStage' : IDL.Func([ImplantCaseId, IDL.Text], [], []),
    'updatePatient' : IDL.Func([Patient], [], []),
    'updatePatientFeedback' : IDL.Func([PatientFeedback], [], []),
    'updateTreatment' : IDL.Func([TreatmentView], [], []),
    'updateTreatmentProgress' : IDL.Func([TreatmentId, IDL.Nat], [], []),
    'updateTreatmentStatus' : IDL.Func([TreatmentId, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };