/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface NewTreatmentView {
    status: string;
    teeth: Uint8Array;
    endDate?: string;
    doctor: string;
    patientId: PatientId;
    clinicId: ClinicId;
    type: string;
    totalUnitsNeeded: bigint;
    unitsCompleted: bigint;
    followUpDates: Array<string>;
    startDate: string;
}
export interface Clinic {
    id: ClinicId;
    name: string;
    address: string;
    phoneNumber: string;
}
export type ImplantCaseId = number;
export interface TreatmentView {
    id: TreatmentId;
    status: string;
    teeth: Uint8Array;
    endDate?: string;
    doctor: string;
    patientId: PatientId;
    clinicId: ClinicId;
    type: string;
    totalUnitsNeeded: bigint;
    unitsCompleted: bigint;
    followUpDates: Array<string>;
    startDate: string;
}
export interface PatientFeedback {
    id: FeedbackId;
    patientId: PatientId;
    clinicId: ClinicId;
    date: string;
    feedback: string;
    googleReviewCompleted: boolean;
    rating: number;
}
export interface NewImplantCaseView {
    healingStartDate?: string;
    patientId: PatientId;
    clinicId: ClinicId;
    crownPlacementDate?: string;
    stage: string;
    surgeryDate?: string;
}
export type ClinicId = number;
export type PatientId = number;
export type TreatmentId = number;
export interface NewAlignerCaseView {
    currentPhase: string;
    endDate?: string;
    patientId: PatientId;
    clinicId: ClinicId;
    stage: string;
    alignersCompleted: bigint;
    hasRefinements: boolean;
    startDate: string;
    totalAligners: bigint;
}
export interface Patient {
    id: PatientId;
    dob: string;
    clinicId: ClinicId;
    name: string;
    email: string;
    address: string;
    gender: string;
    phoneNumber: string;
}
export interface AlignerCase {
    id: AlignerCaseId;
    currentPhase: string;
    endDate?: string;
    patientId: PatientId;
    clinicId: ClinicId;
    stage: string;
    alignersCompleted: bigint;
    hasRefinements: boolean;
    startDate: string;
    totalAligners: bigint;
}
export type AlignerCaseId = number;
export interface ClinicCreation {
    name: string;
    address: string;
    phoneNumber: string;
}
export type ToothNumber = number;
export interface AnalyticsResponse {
    followUpsDueToday: Array<[TreatmentId, string]>;
    overdueFollowUps: Array<[TreatmentId, string]>;
}
export interface NewPatientFeedbackView {
    patientId: PatientId;
    clinicId: ClinicId;
    date: string;
    feedback: string;
    googleReviewCompleted: boolean;
    rating: number;
}
export type FeedbackId = number;
export interface ImplantCase {
    id: ImplantCaseId;
    healingStartDate?: string;
    patientId: PatientId;
    clinicId: ClinicId;
    crownPlacementDate?: string;
    stage: string;
    surgeryDate?: string;
}
export interface UserProfile {
    clinicId?: ClinicId;
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAlignerCase(alignerCaseView: NewAlignerCaseView): Promise<AlignerCaseId>;
    addImplantCase(implantCaseView: NewImplantCaseView): Promise<ImplantCaseId>;
    addPatient(patient: Patient): Promise<PatientId>;
    addPatientFeedback(feedbackView: NewPatientFeedbackView): Promise<FeedbackId>;
    addTreatment(treatmentView: NewTreatmentView): Promise<TreatmentId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createClinic(clinicCreate: ClinicCreation): Promise<Clinic>;
    deleteAlignerCase(id: AlignerCaseId): Promise<void>;
    deleteClinic(id: ClinicId): Promise<void>;
    deleteImplantCase(id: ImplantCaseId): Promise<void>;
    deletePatient(id: PatientId): Promise<void>;
    deletePatientFeedback(id: FeedbackId): Promise<void>;
    deleteTreatment(id: TreatmentId): Promise<void>;
    getAlignerCase(id: AlignerCaseId): Promise<AlignerCase | null>;
    getAllAlignerCases(): Promise<Array<AlignerCase>>;
    getAllClinics(): Promise<Array<Clinic>>;
    getAllImplantCases(): Promise<Array<ImplantCase>>;
    getAllPatientFeedback(): Promise<Array<PatientFeedback>>;
    getAllPatients(): Promise<Array<Patient>>;
    getAllTreatments(): Promise<Array<TreatmentView>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClinic(id: ClinicId): Promise<Clinic | null>;
    getFollowUpAnalytics(): Promise<AnalyticsResponse>;
    getImplantCase(id: ImplantCaseId): Promise<ImplantCase | null>;
    getPatient(id: PatientId): Promise<Patient | null>;
    getPatientFeedback(id: FeedbackId): Promise<PatientFeedback | null>;
    getTreatment(id: TreatmentId): Promise<TreatmentView | null>;
    getUpcomingFollowUps(): Promise<Array<[TreatmentId, string]>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    scheduleFollowUp(treatmentId: TreatmentId, date: string): Promise<void>;
    updateAlignerCase(alignerCase: AlignerCase): Promise<void>;
    updateAlignerCaseStage(id: AlignerCaseId, stage: string): Promise<void>;
    updateClinic(clinic: Clinic): Promise<void>;
    updateImplantCase(implantCase: ImplantCase): Promise<void>;
    updateImplantCaseStage(id: ImplantCaseId, stage: string): Promise<void>;
    updatePatient(patient: Patient): Promise<void>;
    updatePatientFeedback(feedback: PatientFeedback): Promise<void>;
    updateTreatment(treatmentView: TreatmentView): Promise<void>;
    updateTreatmentProgress(id: TreatmentId, completedUnits: bigint): Promise<void>;
    updateTreatmentStatus(id: TreatmentId, status: string): Promise<void>;
}
import type { AlignerCase as _AlignerCase, AlignerCaseId as _AlignerCaseId, Clinic as _Clinic, ClinicId as _ClinicId, ImplantCase as _ImplantCase, ImplantCaseId as _ImplantCaseId, NewAlignerCaseView as _NewAlignerCaseView, NewImplantCaseView as _NewImplantCaseView, NewTreatmentView as _NewTreatmentView, Patient as _Patient, PatientFeedback as _PatientFeedback, PatientId as _PatientId, TreatmentId as _TreatmentId, TreatmentView as _TreatmentView, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAlignerCase(arg0: NewAlignerCaseView): Promise<AlignerCaseId> {
        if (this.processError) {
            try {
                const result = await this.actor.addAlignerCase(to_candid_NewAlignerCaseView_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAlignerCase(to_candid_NewAlignerCaseView_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addImplantCase(arg0: NewImplantCaseView): Promise<ImplantCaseId> {
        if (this.processError) {
            try {
                const result = await this.actor.addImplantCase(to_candid_NewImplantCaseView_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addImplantCase(to_candid_NewImplantCaseView_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addPatient(arg0: Patient): Promise<PatientId> {
        if (this.processError) {
            try {
                const result = await this.actor.addPatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPatient(arg0);
            return result;
        }
    }
    async addPatientFeedback(arg0: NewPatientFeedbackView): Promise<FeedbackId> {
        if (this.processError) {
            try {
                const result = await this.actor.addPatientFeedback(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPatientFeedback(arg0);
            return result;
        }
    }
    async addTreatment(arg0: NewTreatmentView): Promise<TreatmentId> {
        if (this.processError) {
            try {
                const result = await this.actor.addTreatment(to_candid_NewTreatmentView_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTreatment(to_candid_NewTreatmentView_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createClinic(arg0: ClinicCreation): Promise<Clinic> {
        if (this.processError) {
            try {
                const result = await this.actor.createClinic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClinic(arg0);
            return result;
        }
    }
    async deleteAlignerCase(arg0: AlignerCaseId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAlignerCase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAlignerCase(arg0);
            return result;
        }
    }
    async deleteClinic(arg0: ClinicId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClinic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClinic(arg0);
            return result;
        }
    }
    async deleteImplantCase(arg0: ImplantCaseId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteImplantCase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteImplantCase(arg0);
            return result;
        }
    }
    async deletePatient(arg0: PatientId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePatient(arg0);
            return result;
        }
    }
    async deletePatientFeedback(arg0: FeedbackId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePatientFeedback(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePatientFeedback(arg0);
            return result;
        }
    }
    async deleteTreatment(arg0: TreatmentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTreatment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTreatment(arg0);
            return result;
        }
    }
    async getAlignerCase(arg0: AlignerCaseId): Promise<AlignerCase | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlignerCase(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlignerCase(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAlignerCases(): Promise<Array<AlignerCase>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAlignerCases();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAlignerCases();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllClinics(): Promise<Array<Clinic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClinics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClinics();
            return result;
        }
    }
    async getAllImplantCases(): Promise<Array<ImplantCase>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllImplantCases();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllImplantCases();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPatientFeedback(): Promise<Array<PatientFeedback>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPatientFeedback();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPatientFeedback();
            return result;
        }
    }
    async getAllPatients(): Promise<Array<Patient>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPatients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPatients();
            return result;
        }
    }
    async getAllTreatments(): Promise<Array<TreatmentView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTreatments();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTreatments();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClinic(arg0: ClinicId): Promise<Clinic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getClinic(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClinic(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowUpAnalytics(): Promise<AnalyticsResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowUpAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowUpAnalytics();
            return result;
        }
    }
    async getImplantCase(arg0: ImplantCaseId): Promise<ImplantCase | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getImplantCase(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getImplantCase(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPatient(arg0: PatientId): Promise<Patient | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatient(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatient(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPatientFeedback(arg0: FeedbackId): Promise<PatientFeedback | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatientFeedback(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatientFeedback(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTreatment(arg0: TreatmentId): Promise<TreatmentView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTreatment(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTreatment(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUpcomingFollowUps(): Promise<Array<[TreatmentId, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpcomingFollowUps();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpcomingFollowUps();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n31(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n31(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async scheduleFollowUp(arg0: TreatmentId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.scheduleFollowUp(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.scheduleFollowUp(arg0, arg1);
            return result;
        }
    }
    async updateAlignerCase(arg0: AlignerCase): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAlignerCase(to_candid_AlignerCase_n33(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAlignerCase(to_candid_AlignerCase_n33(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateAlignerCaseStage(arg0: AlignerCaseId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAlignerCaseStage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAlignerCaseStage(arg0, arg1);
            return result;
        }
    }
    async updateClinic(arg0: Clinic): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClinic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClinic(arg0);
            return result;
        }
    }
    async updateImplantCase(arg0: ImplantCase): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateImplantCase(to_candid_ImplantCase_n35(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateImplantCase(to_candid_ImplantCase_n35(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateImplantCaseStage(arg0: ImplantCaseId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateImplantCaseStage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateImplantCaseStage(arg0, arg1);
            return result;
        }
    }
    async updatePatient(arg0: Patient): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePatient(arg0);
            return result;
        }
    }
    async updatePatientFeedback(arg0: PatientFeedback): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePatientFeedback(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePatientFeedback(arg0);
            return result;
        }
    }
    async updateTreatment(arg0: TreatmentView): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTreatment(to_candid_TreatmentView_n37(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTreatment(to_candid_TreatmentView_n37(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateTreatmentProgress(arg0: TreatmentId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTreatmentProgress(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTreatmentProgress(arg0, arg1);
            return result;
        }
    }
    async updateTreatmentStatus(arg0: TreatmentId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTreatmentStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTreatmentStatus(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AlignerCase_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlignerCase): AlignerCase {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_ImplantCase_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImplantCase): ImplantCase {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_TreatmentView_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TreatmentView): TreatmentView {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ClinicId]): ClinicId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Clinic]): Clinic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ImplantCase]): ImplantCase | null {
    return value.length === 0 ? null : from_candid_ImplantCase_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Patient]): Patient | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PatientFeedback]): PatientFeedback | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TreatmentView]): TreatmentView | null {
    return value.length === 0 ? null : from_candid_TreatmentView_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AlignerCase]): AlignerCase | null {
    return value.length === 0 ? null : from_candid_AlignerCase_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AlignerCaseId;
    currentPhase: string;
    endDate: [] | [string];
    patientId: _PatientId;
    clinicId: _ClinicId;
    stage: string;
    alignersCompleted: bigint;
    hasRefinements: boolean;
    startDate: string;
    totalAligners: bigint;
}): {
    id: AlignerCaseId;
    currentPhase: string;
    endDate?: string;
    patientId: PatientId;
    clinicId: ClinicId;
    stage: string;
    alignersCompleted: bigint;
    hasRefinements: boolean;
    startDate: string;
    totalAligners: bigint;
} {
    return {
        id: value.id,
        currentPhase: value.currentPhase,
        endDate: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.endDate)),
        patientId: value.patientId,
        clinicId: value.clinicId,
        stage: value.stage,
        alignersCompleted: value.alignersCompleted,
        hasRefinements: value.hasRefinements,
        startDate: value.startDate,
        totalAligners: value.totalAligners
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ImplantCaseId;
    healingStartDate: [] | [string];
    patientId: _PatientId;
    clinicId: _ClinicId;
    crownPlacementDate: [] | [string];
    stage: string;
    surgeryDate: [] | [string];
}): {
    id: ImplantCaseId;
    healingStartDate?: string;
    patientId: PatientId;
    clinicId: ClinicId;
    crownPlacementDate?: string;
    stage: string;
    surgeryDate?: string;
} {
    return {
        id: value.id,
        healingStartDate: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.healingStartDate)),
        patientId: value.patientId,
        clinicId: value.clinicId,
        crownPlacementDate: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.crownPlacementDate)),
        stage: value.stage,
        surgeryDate: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.surgeryDate))
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TreatmentId;
    status: string;
    teeth: Uint8Array;
    endDate: [] | [string];
    doctor: string;
    patientId: _PatientId;
    clinicId: _ClinicId;
    type: string;
    totalUnitsNeeded: bigint;
    unitsCompleted: bigint;
    followUpDates: Array<string>;
    startDate: string;
}): {
    id: TreatmentId;
    status: string;
    teeth: Uint8Array;
    endDate?: string;
    doctor: string;
    patientId: PatientId;
    clinicId: ClinicId;
    type: string;
    totalUnitsNeeded: bigint;
    unitsCompleted: bigint;
    followUpDates: Array<string>;
    startDate: string;
} {
    return {
        id: value.id,
        status: value.status,
        teeth: value.teeth,
        endDate: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.endDate)),
        doctor: value.doctor,
        patientId: value.patientId,
        clinicId: value.clinicId,
        type: value.type,
        totalUnitsNeeded: value.totalUnitsNeeded,
        unitsCompleted: value.unitsCompleted,
        followUpDates: value.followUpDates,
        startDate: value.startDate
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clinicId: [] | [_ClinicId];
    name: string;
}): {
    clinicId?: ClinicId;
    name: string;
} {
    return {
        clinicId: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.clinicId)),
        name: value.name
    };
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AlignerCase>): Array<AlignerCase> {
    return value.map((x)=>from_candid_AlignerCase_n10(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ImplantCase>): Array<ImplantCase> {
    return value.map((x)=>from_candid_ImplantCase_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TreatmentView>): Array<TreatmentView> {
    return value.map((x)=>from_candid_TreatmentView_n18(_uploadFile, _downloadFile, x));
}
function to_candid_AlignerCase_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlignerCase): _AlignerCase {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_ImplantCase_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ImplantCase): _ImplantCase {
    return to_candid_record_n36(_uploadFile, _downloadFile, value);
}
function to_candid_NewAlignerCaseView_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewAlignerCaseView): _NewAlignerCaseView {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_NewImplantCaseView_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewImplantCaseView): _NewImplantCaseView {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_NewTreatmentView_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewTreatmentView): _NewTreatmentView {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_TreatmentView_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TreatmentView): _TreatmentView {
    return to_candid_record_n38(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    currentPhase: string;
    endDate?: string;
    patientId: PatientId;
    clinicId: ClinicId;
    stage: string;
    alignersCompleted: bigint;
    hasRefinements: boolean;
    startDate: string;
    totalAligners: bigint;
}): {
    currentPhase: string;
    endDate: [] | [string];
    patientId: _PatientId;
    clinicId: _ClinicId;
    stage: string;
    alignersCompleted: bigint;
    hasRefinements: boolean;
    startDate: string;
    totalAligners: bigint;
} {
    return {
        currentPhase: value.currentPhase,
        endDate: value.endDate ? candid_some(value.endDate) : candid_none(),
        patientId: value.patientId,
        clinicId: value.clinicId,
        stage: value.stage,
        alignersCompleted: value.alignersCompleted,
        hasRefinements: value.hasRefinements,
        startDate: value.startDate,
        totalAligners: value.totalAligners
    };
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clinicId?: ClinicId;
    name: string;
}): {
    clinicId: [] | [_ClinicId];
    name: string;
} {
    return {
        clinicId: value.clinicId ? candid_some(value.clinicId) : candid_none(),
        name: value.name
    };
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: AlignerCaseId;
    currentPhase: string;
    endDate?: string;
    patientId: PatientId;
    clinicId: ClinicId;
    stage: string;
    alignersCompleted: bigint;
    hasRefinements: boolean;
    startDate: string;
    totalAligners: bigint;
}): {
    id: _AlignerCaseId;
    currentPhase: string;
    endDate: [] | [string];
    patientId: _PatientId;
    clinicId: _ClinicId;
    stage: string;
    alignersCompleted: bigint;
    hasRefinements: boolean;
    startDate: string;
    totalAligners: bigint;
} {
    return {
        id: value.id,
        currentPhase: value.currentPhase,
        endDate: value.endDate ? candid_some(value.endDate) : candid_none(),
        patientId: value.patientId,
        clinicId: value.clinicId,
        stage: value.stage,
        alignersCompleted: value.alignersCompleted,
        hasRefinements: value.hasRefinements,
        startDate: value.startDate,
        totalAligners: value.totalAligners
    };
}
function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ImplantCaseId;
    healingStartDate?: string;
    patientId: PatientId;
    clinicId: ClinicId;
    crownPlacementDate?: string;
    stage: string;
    surgeryDate?: string;
}): {
    id: _ImplantCaseId;
    healingStartDate: [] | [string];
    patientId: _PatientId;
    clinicId: _ClinicId;
    crownPlacementDate: [] | [string];
    stage: string;
    surgeryDate: [] | [string];
} {
    return {
        id: value.id,
        healingStartDate: value.healingStartDate ? candid_some(value.healingStartDate) : candid_none(),
        patientId: value.patientId,
        clinicId: value.clinicId,
        crownPlacementDate: value.crownPlacementDate ? candid_some(value.crownPlacementDate) : candid_none(),
        stage: value.stage,
        surgeryDate: value.surgeryDate ? candid_some(value.surgeryDate) : candid_none()
    };
}
function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: TreatmentId;
    status: string;
    teeth: Uint8Array;
    endDate?: string;
    doctor: string;
    patientId: PatientId;
    clinicId: ClinicId;
    type: string;
    totalUnitsNeeded: bigint;
    unitsCompleted: bigint;
    followUpDates: Array<string>;
    startDate: string;
}): {
    id: _TreatmentId;
    status: string;
    teeth: Uint8Array;
    endDate: [] | [string];
    doctor: string;
    patientId: _PatientId;
    clinicId: _ClinicId;
    type: string;
    totalUnitsNeeded: bigint;
    unitsCompleted: bigint;
    followUpDates: Array<string>;
    startDate: string;
} {
    return {
        id: value.id,
        status: value.status,
        teeth: value.teeth,
        endDate: value.endDate ? candid_some(value.endDate) : candid_none(),
        doctor: value.doctor,
        patientId: value.patientId,
        clinicId: value.clinicId,
        type: value.type,
        totalUnitsNeeded: value.totalUnitsNeeded,
        unitsCompleted: value.unitsCompleted,
        followUpDates: value.followUpDates,
        startDate: value.startDate
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    healingStartDate?: string;
    patientId: PatientId;
    clinicId: ClinicId;
    crownPlacementDate?: string;
    stage: string;
    surgeryDate?: string;
}): {
    healingStartDate: [] | [string];
    patientId: _PatientId;
    clinicId: _ClinicId;
    crownPlacementDate: [] | [string];
    stage: string;
    surgeryDate: [] | [string];
} {
    return {
        healingStartDate: value.healingStartDate ? candid_some(value.healingStartDate) : candid_none(),
        patientId: value.patientId,
        clinicId: value.clinicId,
        crownPlacementDate: value.crownPlacementDate ? candid_some(value.crownPlacementDate) : candid_none(),
        stage: value.stage,
        surgeryDate: value.surgeryDate ? candid_some(value.surgeryDate) : candid_none()
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    teeth: Uint8Array;
    endDate?: string;
    doctor: string;
    patientId: PatientId;
    clinicId: ClinicId;
    type: string;
    totalUnitsNeeded: bigint;
    unitsCompleted: bigint;
    followUpDates: Array<string>;
    startDate: string;
}): {
    status: string;
    teeth: Uint8Array;
    endDate: [] | [string];
    doctor: string;
    patientId: _PatientId;
    clinicId: _ClinicId;
    type: string;
    totalUnitsNeeded: bigint;
    unitsCompleted: bigint;
    followUpDates: Array<string>;
    startDate: string;
} {
    return {
        status: value.status,
        teeth: value.teeth,
        endDate: value.endDate ? candid_some(value.endDate) : candid_none(),
        doctor: value.doctor,
        patientId: value.patientId,
        clinicId: value.clinicId,
        type: value.type,
        totalUnitsNeeded: value.totalUnitsNeeded,
        unitsCompleted: value.unitsCompleted,
        followUpDates: value.followUpDates,
        startDate: value.startDate
    };
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
